name: CI build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [develop, edge]

jobs:
  build:
    if: github.repository_owner == 'BrewBlox'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Set tag variable
        run: |
          echo "TAG=$(echo "${{ github.ref_name }}" | tr '/' '-' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: |
          uv sync

      - name: Test
        run: |
          uv run pytest

      - name: Lint
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --check --diff"

      - name: Build
        run: |
          uv build --sdist

      - name: Upload to Azure Storage
        if: github.event_name != 'pull_request'
        run: >-
          az storage blob upload
          --account-name brewblox
          --container-name ctl
          --sas-token "${{ secrets.CTL_SAS_TOKEN }}"
          --name "${{ env.TAG }}/brewblox-ctl.tar.gz"
          --file "./dist/brewblox_ctl-1.0.0.tar.gz"
          --overwrite
